**NumPy**

**Nokta, Doğru, Düzlem ve Uzay**

In [1]:
import numpy as np

skaler = np.array(90)

vektor = np.array([1,2,3,4,5,6,7])

matris = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

tensor = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

print(skaler)
print(vektor)
print(matris)
print(tensor)

90
[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Neden NumPy**

In [ ]:
import time

z1 = time.time()

liste = []
for a in range(1000000):
    kuvvet = a ** 100
    liste.append(kuvvet)

z2 = time.time()

print(z2-z1)

liste2 = np.arange(1000000)**100

z3 = time.time() # normal basic python'dan 100 kat daha hızlı

print(z3-z2)

1.2607040405273438
0.007000446319580078


**Index and Slicing**

In [5]:
vektor = np.array([0,2,4,5,6,7,8,15])

vektor[0]

np.int64(0)

In [6]:
vektor[-1]

np.int64(15)

In [14]:
print(vektor[:5])
print(vektor[1:5:2])

[0 2 4 5 6]
[2 5]


In [27]:
print(vektor.size)
print(matris.size)
print(tensor.size)

8
9
18


In [25]:
print(vektor.shape)
print(matris.shape)
print(tensor.shape)

(8,)
(3, 3)
(3, 2, 3)


In [29]:
print(vektor.ndim)
print(matris.ndim)
print(tensor.ndim)

1
2
3


In [30]:
print(vektor.dtype)
print(matris.dtype)
print(tensor.dtype)

int64
int64
int64


**NumPy Veri Tipi Değiştirme**

In [31]:
sayilar = np.array([1,2,3,4,5,6])

sayilar.dtype

dtype('int64')

In [32]:
sayilar = np.array([1,2,3,4,5,6.1])

sayilar.dtype

dtype('float64')

In [33]:
sayilar = np.array([1,2,3,4,5,6,"hasan"])

sayilar.dtype

dtype('<U21')

In [37]:
sayilar = np.array([1,2,3,4,5,6])

sayilar = sayilar.astype("int32")

sayilar.dtype

dtype('int32')

In [38]:
matris = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
matris[0]

array([1, 2, 3, 4])

In [44]:
matris[0,0::1]

array([1, 2, 3, 4])

In [ ]:
tensor = np.array([[[1,2,3,4],
                    [1,2,3,4],
                    [1,2,3,4]],
                   [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                   [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
tensor

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [73]:
tensor[2::1,0,2::1]

array([[3, 4]])

**Random Matris Oluşturma**

In [74]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [75]:
np.random.randint(0,5)

4

In [81]:
np.random.randint(0,10)

8

In [82]:
np.random.randint(0,5,(4,4))

array([[2, 1, 1, 3],
       [4, 0, 0, 0],
       [0, 2, 1, 3],
       [3, 3, 4, 1]], dtype=int32)

In [83]:
np.random.randint(0,5,(4,4)) ** 10

array([[1048576,       1,   59049,   59049],
       [   1024,    1024,    1024, 1048576],
       [      0,    1024, 1048576, 1048576],
       [      1,       0,       0,       0]], dtype=int32)

In [ ]:
np.random.randint(0,5,(4,4)) * 10

array([[40, 30, 30, 10],
       [ 0, 20, 20, 10],
       [20, 20, 30, 10],
       [10,  0, 30,  0]], dtype=int32)

In [85]:
np.random.randint(0,5,(4,4)) / 10

array([[0.4, 0.2, 0.2, 0.1],
       [0.4, 0.1, 0.1, 0.4],
       [0. , 0.1, 0.4, 0.2],
       [0.3, 0. , 0.1, 0.3]])

In [87]:
np.random.randint(0,5,(4,4)) - 10

array([[ -9,  -7,  -7,  -6],
       [ -8, -10,  -9,  -9],
       [ -8,  -9, -10,  -7],
       [ -6,  -6,  -6,  -8]], dtype=int32)

In [88]:
np.random.randint(0,5,(4,4)) + 10

array([[10, 12, 14, 10],
       [11, 13, 13, 10],
       [10, 13, 14, 13],
       [13, 14, 11, 11]], dtype=int32)

**Arange ile Vektör Oluşturma**

In [89]:
liste = [1,2,3,4,5,6]

milyon = np.arange(1000000)

In [90]:
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

**linspace() ile Vektör Oluşturma**

In [92]:
bol = np.linspace(5,25,16)

bol

array([ 5.        ,  6.33333333,  7.66666667,  9.        , 10.33333333,
       11.66666667, 13.        , 14.33333333, 15.66666667, 17.        ,
       18.33333333, 19.66666667, 21.        , 22.33333333, 23.66666667,
       25.        ])

In [94]:
bol2 = np.linspace(5,100,16)

bol2

array([  5.        ,  11.33333333,  17.66666667,  24.        ,
        30.33333333,  36.66666667,  43.        ,  49.33333333,
        55.66666667,  62.        ,  68.33333333,  74.66666667,
        81.        ,  87.33333333,  93.66666667, 100.        ])

In [95]:
bol3 = bol2 - bol

bol3

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75.])

**reshape() Metodu**

In [97]:
m1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
m1.shape

(3, 4)

In [100]:
np.random.randint(0,2,(8,5))

array([[0, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [101]:
np.linspace(0,20,30).reshape(6,5)

array([[ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069],
       [ 3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655],
       [ 6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241],
       [10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828],
       [13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414],
       [17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ]])

**copy() ve view() Metodları**

In [102]:
matris = np.random.randint(0,5,(4,4))

matris

array([[2, 4, 2, 2],
       [4, 2, 0, 3],
       [3, 1, 1, 2],
       [2, 1, 1, 1]], dtype=int32)

In [104]:
matris2 = matris.view()
matris_2 = matris.copy()

In [105]:
print(matris2)
print(matris_2)

[[2 4 2 2]
 [4 2 0 3]
 [3 1 1 2]
 [2 1 1 1]]
[[2 4 2 2]
 [4 2 0 3]
 [3 1 1 2]
 [2 1 1 1]]


**ones(), zeros() ve full() Matris Oluşturma Metodları**

In [124]:
print(np.ones([1,2]))

print(np.zeros([5,5]))

print(np.full((10,10),2))

[[1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]]


**eye(), diag(), identity() Metodları**

In [ ]:
print(np.eye(3,5,k=1)) # birim matris oluşturur nxm tipinde ve k = birim matrisin ne kadar kaydırılacağı

print(np.diag([1,1,1,1]))

print(np.identity(5))

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Matrislerde Matematiksel İşlemler**

In [141]:
m1 = np.ones((5,5))
m2 = np.full((5,5),19)

print(f"{m1} ve {m2}")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] ve [[19 19 19 19 19]
 [19 19 19 19 19]
 [19 19 19 19 19]
 [19 19 19 19 19]
 [19 19 19 19 19]]


In [143]:
print(f"{m1 + m2} toplam")

[[20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]] toplam


In [145]:
print(f"{m1 * m2} çarpım")

[[19. 19. 19. 19. 19.]
 [19. 19. 19. 19. 19.]
 [19. 19. 19. 19. 19.]
 [19. 19. 19. 19. 19.]
 [19. 19. 19. 19. 19.]] çarpım


In [146]:
print(f"{m1 - m2} çıkarma")

[[-18. -18. -18. -18. -18.]
 [-18. -18. -18. -18. -18.]
 [-18. -18. -18. -18. -18.]
 [-18. -18. -18. -18. -18.]
 [-18. -18. -18. -18. -18.]] çıkarma


In [147]:
print(f"{m1 ** m2} üs")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] üs


In [148]:
print(f"{m1 / m2} bölme")

[[0.05263158 0.05263158 0.05263158 0.05263158 0.05263158]
 [0.05263158 0.05263158 0.05263158 0.05263158 0.05263158]
 [0.05263158 0.05263158 0.05263158 0.05263158 0.05263158]
 [0.05263158 0.05263158 0.05263158 0.05263158 0.05263158]
 [0.05263158 0.05263158 0.05263158 0.05263158 0.05263158]] bölme


In [149]:
print(f"{m1 @ m2} matris çarpımı")

[[95. 95. 95. 95. 95.]
 [95. 95. 95. 95. 95.]
 [95. 95. 95. 95. 95.]
 [95. 95. 95. 95. 95.]
 [95. 95. 95. 95. 95.]] matris çarpımı


**Mantıksal Operatörler ve Filtreleme**

In [152]:
matris = np.random.randint(0,10,(5,5))

matris

array([[1, 7, 4, 1, 1],
       [9, 0, 7, 7, 3],
       [7, 6, 6, 4, 7],
       [7, 4, 4, 0, 0],
       [5, 6, 7, 2, 5]], dtype=int32)

In [153]:
matris>5

array([[False,  True, False, False, False],
       [ True, False,  True,  True, False],
       [ True,  True,  True, False,  True],
       [ True, False, False, False, False],
       [False,  True,  True, False, False]])

In [154]:
matris[matris>5]

array([7, 9, 7, 7, 7, 6, 6, 7, 7, 6, 7], dtype=int32)

In [ ]:
matris[matris==5]

array([5, 5], dtype=int32)

In [156]:
matris[matris==5].size

2

In [159]:
sifir = matris == 0
cift = matris%2 == 0
bir = matris == 1

print(matris[cift])
print(matris[sifir])
print(matris[bir])

[4 0 6 6 4 4 4 0 0 6 2]
[0 0 0]
[1 1 1]


In [162]:
print(matris[ cift & sifir & bir ])

[]
